[workspace]
members = [
    "bin"
]

resolver = "2"

[workspace.package]
rust-version = "1.90.0"
edition = "2024"
name = "mini-redis"

[workspace.dependencies]

[workspace.lints]
clippy.pedantic = { level = "allow", priority = -1}
clippy.unnecessary_wraps = "warn"