services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend_service
    ports:
      - "8090:8090"
  
  client: 
    build: 
      context: .
      dockerfile: Dockerfile.client
    container_name: client_service
    depends_on:
      - backend
    ports:
      - "8080:8080"
