FROM rust:bookworm as builder
# ENV TMPDIR=/var/tmp
RUN apt update && apt install -y \
    libssl-dev \
    pkg-config \
    build-essential \
    musl-tools
WORKDIR /app/client
COPY client .
RUN cargo build --release

FROM debian:bookworm-slim
# ENV TMPDIR=/var/tmp
RUN ls
RUN apt update && apt install -y build-essential musl-tools 
COPY --from=builder /app/client/target/release/client /usr/local/bin/client
EXPOSE 8080
CMD ["client"]