[package]
name = "inference"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["json", "blocking"] }
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
