[package]
name = "rnet-peer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
anyhow = {workspace = true}
async-trait = {workspace = true}
serde = { workspace = true }
bincode = { workspace = true }
