[package]
name = "rnet-core-host"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {workspace = true}
anyhow = {workspace = true}
async-trait = {workspace = true}
tracing = "0.1"

rnet-tcp = {path = "../../transport/tcp"}
rnet-core-traits = {path = "../../core/traits"}
